### ISSUE TITLE
Adding/Removing Models

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-rendering#1]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/1)) by Pedro Osório (Bitbucket: [pedroosorio88](https://bitbucket.org/%7B1abaad62-2c38-4702-8192-4d22bb14b252%7D/)).**

----------------------------------------
Hi IGN team !

I'm working on a custom gazebo client and i'm using IGN to render the scene. Whenever i add a model it throws : 

[Err] [SceneManager.cc:1639] invalid parent name: minho_robot_2::base
[Wrn] [SceneManager.cc:1640] using scene root node

The model isn't displayed properly at first. 

![before.png](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/zq9ear/images/3511116263-before.png)

If i close and re-open the client, now it is properly displayed. 

![after.png](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/zq9ear/images/3235579331-after.png)

It means that "refreshing" makes everything work correctly, as parents are correctly assigned. What am i doing wrong here, where is this behavior coming from ?

**Comment by azeey** [comment]
This is a very old issue, so I'll go ahead and close it. Feel free to open if the problem is still relevant

**Comment by mjcarroll** [comment]
So I think maybe this is also covered by: https://github.com/gazebosim/gz-sim/pull/824
