### ISSUE TITLE
Ogre crash when selecting "sunVisual"

### ISSUE THREAD

**Issue by heeplr** [gazebosim/gz-rendering#1000]
## Environment
* OS Version: gentoo
* Source or binary build?
  * source tarball:
```
* dependency graph for sci-libs/gz-rendering-8.1.1
 `--  sci-libs/gz-rendering-8.1.1  ~amd64 
   `--  media-libs/freeimage-3.18.0-r11  (media-libs/freeimage) amd64 
   `--  dev-games/ogre-1.9.0-r3  (dev-games/ogre) amd64  [-double-precision]
   `--  dev-build/gz-cmake-3.5.3  (>=dev-build/gz-cmake-3.5.3) ~amd64 
   `--  sci-libs/gz-math-7.4.0  (>=sci-libs/gz-math-7.4.0) ~amd64 
   `--  sci-libs/gz-common-5.6.0  (>=sci-libs/gz-common-5.6.0) ~amd64 
   `--  sci-libs/gz-plugin-2.0.3  (>=sci-libs/gz-plugin-2.0.3) ~amd64 
   `--  sci-libs/gz-utils-2.2.0  (>=sci-libs/gz-utils-2.2.0) ~amd64 
   `--  app-alternatives/ninja-1  (app-alternatives/ninja) amd64 
   `--  dev-build/cmake-3.27.9  (>=dev-build/cmake-3.20.5) amd64 
```

* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section. 
    - Rendering plugin: ogre 
      - [ ] Sensor rendering error. 
      - [X] GUI rendering error. 
    - EGL headless mode:
      - [ ] Running in EGL headless mode 
    - Generally, mention all circumstances that might affect rendering capabilities: 
      - [ ] running on a dual GPU machine (integrated GPU + discrete GPU)
      - [ ] running on a multi-GPU machine (it has multiple discrete GPUs)
      - [X] running on real hardware
      - [ ] running in virtual machine
      - [ ] running in Docker/Singularity
      - [ ] running remotely (e.g. via SSH)
      - [ ] running in a cloud
      - [ ] using VirtualGL, XVFB, Xdummy, XVNC or other indirect rendering utilities
      - [X] GPU is concurrently used for other tasks
        - [X] desktop acceleration
        - [ ] video decoding (i.e. a playing Youtube video)
        - [ ] video encoding
        - [ ] CUDA/ROCm computations (Tensorflow, Torch, Caffe running)
        - [ ] multiple simulators running at the same time
      - [ ] other...
    - Rendering system info:
      - On Linux, provide the outputs of the following commands:
          ```bash
          LANG=C lspci -nn | grep VGA  # might require installing pciutils
          00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)

          echo "$DISPLAY"
          :0.0

          LANG=C glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'  # might require installing mesa-utils package
          direct rendering: Yes
          Preferred profile: core (0x1)
          Max core profile version: 4.6
          Max compat profile version: 4.6
          Max GLES1 profile version: 1.1
          Max GLES[23] profile version: 3.2
          OpenGL vendor string: Intel
          OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
          OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.9
          OpenGL core profile shading language version string: 4.60
          OpenGL core profile context flags: (none)
          OpenGL core profile profile mask: core profile
          OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.9
          OpenGL shading language version string: 4.60
          OpenGL context flags: (none)
          OpenGL profile mask: compatibility profile
          OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.9
          OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

          ps aux | grep Xorg
          root      264120  0.0  0.0   6536  2304 pts/12   S+   11:12   0:00 grep --colour=auto Xorg

          sudo env LANG=C X -version  # if you don't have root access, try to tell the version of Xorg e.g. via package manager
          X.Org X Server 1.21.1.10
          X Protocol Version 11, Revision 0
          Current Operating System: Linux upquark 6.3.0-gentoo #2 SMP PREEMPT_DYNAMIC Mon Aug 14 17:12:16 CEST 2023 x86_64
          Kernel command line: BOOT_IMAGE=/vmlinuz-6.3.0-gentoo root=/dev/nvme0n1p2 ro init=/usr/lib/systemd/systemd usbcore.autosuspend=60 i915.i915_enable_fbc=1
 
          Current version of pixman: 0.42.2
          Before reporting problems, check http://wiki.x.org
          to make sure that you have the latest version.          ```

    - [X] Please, attach the ogre.log or ogre2.log file from  `~/.gz/rendering` <!-- Choose the relevant version based on what you checked in the "Rendering plugin" question. -->

[ogre.log](https://github.com/gazebosim/gz-rendering/files/15282365/ogre.log)

## Description
* Expected behavior: no crash
* Actual behavior: crash

## Steps to reproduce
<!-- Provide steps so we can try to reproduce this issue -->

1. create robot.sdf with empty world from [first snippet of tutorial](https://gazebosim.org/docs/garden/building_robot)
2. launch ```gz sim --render-engine=ogre robot.sdf```
3. uncollapse "sun" in entity tree
4. LMB click on "sunVisual"

## Output
```
$ LC_ALL="C" LC_LANG="C" gz sim -v 4 --render-engine=ogre robot.sdf                                                                     
[Msg] Gazebo Sim GUI    v8.3.0                                                                                                                                                   
[Dbg] [gz.cc:166] Subscribing to [/gazebo/starting_world].                                                                                                                       
[Dbg] [Gui.cc:263] Waiting for subscribers to [/gazebo/starting_world]...
[Dbg] [gz.cc:168] Waiting for a world to be set from the GUI...
[Msg] Received world [robot.sdf] from the GUI.
[Dbg] [gz.cc:172] Unsubscribing from [/gazebo/starting_world].
[Msg] Gazebo Sim Server v8.3.0
[Msg] Loading SDF world file[/home/daniel/code/3rdparty/gazebo/robot.sdf].
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-daniel'
[Dbg] [Application.cc:96] Initializing application.
[Dbg] [Application.cc:170] Qt using OpenGL graphics interface
[GUI] [Dbg] [Application.cc:657] Create main window
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:860] Loaded [gz::physics::dartsim::Plugin] from library [/usr/lib64/gz-physics-7/engine-plugins/libgz-physics-dartsim-plugin.so]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::Physics] for entity [1]
[Msg] Create service on [/world/car_world/create]
[Msg] Remove service on [/world/car_world/remove]
[Msg] Pose service on [/world/car_world/set_pose]
[Msg] Pose service on [/world/car_world/set_pose_vector]
[Msg] Light configuration service on [/world/car_world/light_config]
[Msg] Physics service on [/world/car_world/set_physics]
[Msg] SphericalCoordinates service on [/world/car_world/set_spherical_coordinates]
[Msg] Enable collision service on [/world/car_world/enable_collision]
[Msg] Disable collision service on [/world/car_world/disable_collision]
[Msg] Material service on [/world/car_world/visual_config]
[Msg] Material service on [/world/car_world/wheel_slip]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [SystemManager.cc:74] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/car_world/control], [/world/car_world/control/state] and [/world/car_world/playback/control]
[Msg] Serving GUI information on [/world/car_world/gui/info]
[Msg] World [car_world] initialized with [lms] physics profile.
[Msg] Serving world SDF generation service on [/world/car_world/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource path resolve service on [/gazebo/resource_paths/resolve].                                                                                               [155/1940]
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[GUI] [Dbg] [PathManager.cc:68] Requesting resource paths through [/gazebo/resource_paths/get]
[GUI] [Dbg] [Gui.cc:343] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[GUI] [Dbg] [PathManager.cc:57] Received resource paths.
[GUI] [Dbg] [Gui.cc:401] Requesting GUI from [/world/car_world/gui/info]...
[GUI] [Dbg] [GuiRunner.cc:149] Requesting initial state from [/world/car_world/state]...
[GUI] [Msg] Loading config [/home/daniel/.gz/sim/8/gui.config]
[GUI] [Dbg] [Application.cc:528] Loading plugin [MinimalScene]
[GUI] [Dbg] [MinimalScene.cc:802] Creating gz-rendering interface for OpenGL
[GUI] [Dbg] [MinimalScene.cc:802] Creating gz-rendering interface for OpenGL
[GUI] [Dbg] [MinimalScene.cc:986] Creating render thread interface for OpenGL
[GUI] [Dbg] [MinimalScene.cc:802] Creating gz-rendering interface for OpenGL
[GUI] [Dbg] [MinimalScene.cc:986] Creating render thread interface for OpenGL
[GUI] [Msg] Added plugin [3D View] to main window
[GUI] [Msg] Loaded plugin [MinimalScene] from path [/usr/lib64/gz-gui-8/plugins/libMinimalScene.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [EntityContextMenuPlugin]
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is manag[115/1940]
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Msg] Added plugin [Entity Context Menu] to main window
[GUI] [Msg] Loaded plugin [EntityContextMenuPlugin] from path [/usr/lib64/gz-sim-8/plugins/gui/libEntityContextMenuPlugin.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [GzSceneManager]
[GUI] [Msg] Added plugin [Scene Manager] to main window
[GUI] [Msg] Loaded plugin [GzSceneManager] from path [/usr/lib64/gz-sim-8/plugins/gui/libGzSceneManager.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [InteractiveViewControl]
[GUI] [Msg] Camera view controller topic advertised on [/gui/camera/view_control]
[GUI] [Msg] Camera reference visual topic advertised on [/gui/camera/view_control/reference_visual]
[GUI] [Msg] Camera view control sensitivity advertised on [/gui/camera/view_control/sensitivity]
[GUI] [Msg] Added plugin [Interactive view control] to main window
[GUI] [Msg] Loaded plugin [InteractiveViewControl] from path [/usr/lib64/gz-gui-8/plugins/libInteractiveViewControl.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [CameraTracking]
[GUI] [Msg] Added plugin [Camera tracking] to main window
[GUI] [Msg] Loaded plugin [CameraTracking] from path [/usr/lib64/gz-gui-8/plugins/libCameraTracking.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [MarkerManager]
[GUI] [Msg] Listening to stats on [/world/car_world/stats]
[GUI] [Msg] Added plugin [Marker Manager] to main window
[GUI] [Msg] Loaded plugin [MarkerManager] from path [/usr/lib64/gz-gui-8/plugins/libMarkerManager.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [SelectEntities]
[GUI] [Msg] Added plugin [Select entities] to main window
[GUI] [Msg] Loaded plugin [SelectEntities] from path [/usr/lib64/gz-sim-8/plugins/gui/libSelectEntities.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [Spawn]
[GUI] [Msg] Added plugin [Spawn] to main window
[GUI] [Msg] Loaded plugin [Spawn] from path [/usr/lib64/gz-sim-8/plugins/gui/libSpawn.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [VisualizationCapabilities]
[GUI] [Msg] View as transparent service on [/gui/view/transparent]
[GUI] [Msg] View as wireframes service on [/gui/view/wireframes]
[GUI] [Msg] View center of mass service on [/gui/view/com]
[GUI] [Msg] View inertia service on [/gui/view/inertia]
[GUI] [Msg] View collisions service on [/gui/view/collisions]
[GUI] [Msg] View joints service on [/gui/view/joints]
[GUI] [Msg] View frames service on [/gui/view/frames]
[GUI] [Msg] Added plugin [Visualization capabilities] to main window
[GUI] [Msg] Loaded plugin [VisualizationCapabilities] from path [/usr/lib64/gz-sim-8/plugins/gui/libVisualizationCapabilities.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [WorldControl]
[GUI] [Msg] Using world control service [/world/car_world/control]
[GUI] [Msg] Listening to stats on [/world/car_world/stats]
[GUI] [Dbg] [WorldControl.cc:237] Using an event to share WorldControl msgs with the server
[GUI] [Msg] Added plugin [World control] to main window                                                                                                                 [75/1940]
[GUI] [Msg] Loaded plugin [WorldControl] from path [/usr/lib64/gz-gui-8/plugins/libWorldControl.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [WorldStats]
[GUI] [Msg] Listening to stats on [/world/car_world/stats]
[GUI] [Msg] Added plugin [World stats] to main window
[GUI] [Msg] Loaded plugin [WorldStats] from path [/usr/lib64/gz-gui-8/plugins/libWorldStats.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [Shapes]
[GUI] [Msg] Added plugin [Shapes] to main window
[GUI] [Msg] Loaded plugin [Shapes] from path [/usr/lib64/gz-sim-8/plugins/gui/libShapes.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [Lights]
[GUI] [Msg] Added plugin [Lights] to main window
[GUI] [Msg] Loaded plugin [Lights] from path [/usr/lib64/gz-sim-8/plugins/gui/libLights.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [TransformControl]
[GUI] [Msg] Added plugin [Transform control] to main window
[GUI] [Msg] Loaded plugin [TransformControl] from path [/usr/lib64/gz-sim-8/plugins/gui/libTransformControl.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [Screenshot]
[GUI] [Msg] Screenshot service on [/gui/screenshot]
[GUI] [Msg] Added plugin [Screenshot] to main window
[GUI] [Msg] Loaded plugin [Screenshot] from path [/usr/lib64/gz-gui-8/plugins/libScreenshot.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [CopyPaste]
[GUI] [Msg] Added plugin [Copy/Paste] to main window
[GUI] [Msg] Loaded plugin [CopyPaste] from path [/usr/lib64/gz-sim-8/plugins/gui/libCopyPaste.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [ComponentInspector]
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:547] Creating PostUpdate worker threads: 2
[Dbg] [SimulationRunner.cc:558] Creating postupdate worker thread (0)
[Msg] Serving scene information on [/world/car_world/scene/info]
[Msg] Serving graph information on [/world/car_world/scene/graph]
[Msg] Serving full state on [/world/car_world/state]
[Msg] Serving full state (async) on [/world/car_world/state_async]
[Msg] Publishing scene information on [/world/car_world/scene/info]
[Msg] Publishing entity deletions on [/world/car_world/scene/deletion]
[Msg] Publishing state changes on [/world/car_world/state]
[Msg] Publishing pose messages on [/world/car_world/pose/info]
[Msg] Publishing dynamic pose messages on [/world/car_world/dynamic_pose/info]
[Dbg] [EntityComponentManager.cc:1655] Updated state thread iterators: 8 threads processing around 2 entities each.
[Wrn] [Component.hh:144] Trying to serialize component with data type [N3sdf3v145WorldE], which doesn't have `operator<<`. Component will not be serialized.
[GUI] [Msg] Added plugin [Component inspector] to main window
[GUI] [Msg] Loaded plugin [ComponentInspector] from path [/usr/lib64/gz-sim-8/plugins/gui/libComponentInspector.so]
[GUI] [Dbg] [Application.cc:528] Loading plugin [EntityTree]                                                                                                            [35/1940]
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityTree/EntityTree.qml:148:7: QML ToolButton: Detected anchors on an item that is managed by a layout. This is undefined behavior
; use Layout.alignment instead.
[GUI] [Msg] Added plugin [Entity tree] to main window
[GUI] [Msg] Loaded plugin [EntityTree] from path [/usr/lib64/gz-sim-8/plugins/gui/libEntityTree.so]
[GUI] [Dbg] [Application.cc:398] Loading window config
[GUI] [Msg] Using server control service [/server_control]
[GUI] [Dbg] [Application.cc:671] Applying config
[GUI] [Wrn] [Component.hh:189] Trying to deserialize component with data type [N3sdf3v145WorldE], which doesn't have `operator>>`. Component will not be deserialized.
[GUI] [Wrn] [Application.cc:908] [QT] file::/WorldStats/WorldStats.qml:53:3: QML RowLayout: Binding loop detected for property "x"
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a 
layout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Wrn] [Application.cc:908] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a la
yout. This is undefined behavior; use Layout.alignment instead.
[GUI] [Dbg] [MinimalScene.cc:802] Creating gz-rendering interface for OpenGL
[GUI] [Dbg] [MinimalScene.cc:986] Creating render thread interface for OpenGL
[GUI] [Msg] Loading plugin [gz-rendering-ogre]
[GUI] [Dbg] [MinimalScene.cc:749] Create scene [scene]
[GUI] [Dbg] [MinimalScene.cc:1037] Creating texture node render interface for OpenGL
[GUI] [Dbg] [TransformControl.cc:453] TransformControl plugin is using camera [scene::Camera(65527)]
[GUI] [Dbg] [Spawn.cc:308] Spawn plugin is using camera [scene::Camera(65527)]
[GUI] [Dbg] [SelectEntities.cc:452] SelectEntities plugin is using camera [scene::Camera(65527)]
[GUI] [Dbg] [MarkerManager.cc:169] Advertise /marker/list service.
[GUI] [Dbg] [MarkerManager.cc:179] Advertise /marker/list.
[GUI] [Dbg] [MarkerManager.cc:189] Advertise /marker_array.
[GUI] [Dbg] [CameraTracking.cc:172] CameraTrackingPrivate plugin is moving camera [scene::Camera(65527)]
[GUI] [Msg] Move to service on [/gui/move_to]
[GUI] [Msg] Follow service on [/gui/follow]
[GUI] [Msg] Move to pose service on [/gui/move_to/pose]
[GUI] [Msg] Camera pose topic advertised on [/gui/camera/pose]
[GUI] [Msg] Follow offset service on [/gui/follow/offset]
[GUI] [Dbg] [InteractiveViewControl.cc:176] InteractiveViewControl plugin is moving camera [scene::Camera(65527)]
[GUI] [Dbg] [EntityContextMenuPlugin.cc:79] Entity context menu plugin is using camera [scene::Camera(65527)]
gz sim gui: /var/tmp/portage/dev-games/ogre-1.9.0-r3/work/ogre-1.9.0/OgreMain/include/OgreAxisAlignedBox.h:251: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const
 Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
Stack trace (most recent call last) in thread 264064:
#31   Object "/usr/lib64/libQt5Core.so.5", at 0x7f51f0a79ef2, in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
#30   Object "/usr/lib64/libQt5Core.so.5", at 0x7f51f0a76ab7, in QCoreApplication::notifyInternal2(QObject*, QEvent*)
#29   Object "/usr/lib64/libQt5Widgets.so.5", at 0x7f51f0162fed, in QApplicationPrivate::notify_helper(QObject*, QEvent*)
#28   Object "/usr/lib64/libQt5Core.so.5", at 0x7f51f0a9fe11, in QObject::event(QEvent*) 
#27   Object "/usr/lib64/gz-gui-8/plugins/libMinimalScene.so", at 0x7f51e008f964, in gz::gui::plugins::RenderThread::RenderNext(gz::gui::plugins::RenderSync*)
#26   Object "/usr/lib64/gz-gui-8/plugins/libMinimalScene.so", at 0x7f51e00a06d4, in gz::gui::plugins::RenderThreadRhiOpenGL::RenderNext(gz::gui::plugins::RenderSync*)
#25   Object "/usr/lib64/gz-gui-8/plugins/libMinimalScene.so", at 0x7f51e00981fb, in gz::gui::plugins::GzRenderer::Render(gz::gui::plugins::RenderSync*, gz::gui::plugins::Render
ThreadRhi&)
#24   Object "/usr/lib64/gz-rendering-8/engine-plugins/libgz-rendering-ogre.so", at 0x7f51477bb6ce, in gz::rendering::v8::BaseCamera<gz::rendering::v8::OgreSensor>::Update()
#23   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51473123a3, in Ogre::RenderTarget::update(bool)
#22   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f5147313068, in Ogre::RenderTarget::updateImpl()
#21   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f5147311d0b, in Ogre::RenderTarget::_updateAutoUpdatedViewports(bool)
#20   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f5147312687, in Ogre::RenderTarget::_updateViewport(Ogre::Viewport*, bool)
#19   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51471a64da, in Ogre::Camera::_renderScene(Ogre::Viewport*, bool)
#18   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514735af63, in Ogre::SceneManager::_renderScene(Ogre::Camera*, Ogre::Viewport*, bool)
#17   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514733e008, in Ogre::SceneManager::_updateSceneGraph(Ogre::Camera*)
#16   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514736b0df, in Ogre::SceneNode::_update(bool, bool)
#15   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51472b06d3, in Ogre::Node::_update(bool, bool)
#14   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514736b0df, in Ogre::SceneNode::_update(bool, bool)
#13   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51472b06d3, in Ogre::Node::_update(bool, bool)
#12   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514736b0df, in Ogre::SceneNode::_update(bool, bool)
#11   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51472b06d3, in Ogre::Node::_update(bool, bool)
#10   Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f514736b0df, in Ogre::SceneNode::_update(bool, bool)
#9    Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51472b06d3, in Ogre::Node::_update(bool, bool)
#8    Object "/usr/lib64/OGRE/Plugin_OctreeSceneManager.so", at 0x7f5165312056, in Ogre::OctreeNode::_updateBounds()
#7    Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51472ada70, in Ogre::MovableObject::getWorldBoundingBox(bool) const
#6    Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51471ee3c3, in 
#5    Object "/usr/lib64/libOgreMain.so.1.9.0", at 0x7f51471e5012, in 
#4    Object "/lib64/libc.so.6", at 0x7f51f6675e81, in __assert_fail
#3    Object "/lib64/libc.so.6", at 0x7f51f6666414, in 
#2    Object "/lib64/libc.so.6", at 0x7f51f66664f1, in abort
#1    Object "/lib64/libc.so.6", at 0x7f51f667d251, in raise
#0    Object "/lib64/libc.so.6", at 0x7f51f66caacc, in 
Aborted (Signal sent by tkill() 263982 1000) 
[Dbg] [SignalHandler.cc:142] Received signal[2].
[Dbg] [ServerPrivate.cc:115] Server received signal[2]
[Dbg] [gz.cc:434] Shutting down gz-sim-server
[Dbg] [SimulationRunner.cc:574] Exiting postupdate worker thread (0)
```

**Comment by iche033** [comment]
looks like it could be coming from ogre 1.x's implementation [WireBox](https://github.com/gazebosim/gz-rendering/blob/gz-rendering8/ogre/src/OgreWireBox.cc) that gets created when an object is [highlighed](https://github.com/gazebosim/gz-sim/blob/6af74459f4b0f5a2a33fa112e24ac50633a90d3b/src/gui/plugins/select_entities/SelectEntities.cc#L301) on selection
