### ISSUE TITLE
How to add DynamicLines

### ISSUE THREAD

**Issue by Masa0u0** [gazebosim/gz-rendering#1039]
In Gazebo Classic, we can create a DynamicLine by inheriting from gazebo::VisualPlugin and invoking gazebo::rendering::Visual::createDynamicLine. Is it possible to perform a similar operation in Gazebo Harmonic? Although the class gz::rendering::OgreDynamicLines does exist, I am unsure of the method to generate it within a scene.

**Comment by iche033** [comment]
there is currently no API to create a dynamic line. The alternative is to use a [Marker](https://github.com/gazebosim/gz-rendering/blob/gz-rendering8/include/gz/rendering/Marker.hh) and set the type to `gz::rendering::MarkerType::MT_LINE_LIST` - this tells the marker to use dynamic lines. As an example, the [MarkerMananger](https://github.com/gazebosim/gz-sim/blob/gz-sim8/src/rendering/MarkerManager.cc) in gz-sim uses this to draw shapes and lines in the scene.

**Comment by Masa0u0** [comment]
@iche033 
Thank you very much!
