### ISSUE TITLE
OgreText not rendering after #66

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-rendering#25]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/25)) by Deanna Hood (Bitbucket: [d_hood](https://bitbucket.org/%7B40d490b4-7de9-4c89-ac1c-2219a22057eb%7D/)).**

----------------------------------------
I have developed https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/137 using a pinned version of ignition rendering.

I just updated to the default branch and noticed that the MoveableText I was using no longer displays.

I have narrowed it down to a change [between these commits ](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/branches/compare/f247..9a91), i.e. https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/66. (9a91 it works, f247 it doesn't render). I saw that that PR was to improve performance.. perhaps it is a little too efficient now? :smile:

I'm testing with `ign gui -c src/ign_gui/examples/config/display_plugins.config` on [this branch ](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/137).

**Comment by iche033** [comment]
no longer able to reproduce this issue.
