### ISSUE TITLE
Renable tests in actions

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-rendering#44]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/issues/44)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
[Pull request #142](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/pull-requests/142) disabled tests in pipelines because they are flaky. This issue is resolved when the tests are enabled and not flaky.

**Comment by chapulina** [comment]
Tests have been ported to GitHub actions and are enabled. Until https://github.com/ignition-tooling/ubuntu-bionic-ci-action/issues/6 is solved, they can't return failure though.
