### ISSUE TITLE
Heightmaps don't work properly with segmentation camera

### ISSUE THREAD

**Issue by adlarkin** [gazebosim/gz-rendering#444]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build?
  Source: https://github.com/ignitionrobotics/ign-rendering/commit/eb7d6eaa5c6129fd76acbe222f6ca8655599342a

## Description
* Expected behavior: Heightmaps shouldn't be included in the segmentation output if they don't have a label.
* Actual behavior: Heightmaps can be seen if they aren't labeled.

A temporary fix that disables heightmap from the segmentation camera completely has been made in #443, but we should implement a solution that allows users to apply a label to the heightmap if they desire.

## Steps to reproduce

1. Run a world with a heightmap and semantic segmentation sensor in `ign-gazebo` (the fortress demo world has both)
2. View the segmentation output in the gazebo GUI by viewing the relevant colored map segmentation topic
3. You'll see a part of the heightmap in the segmentation output

## Output
![partial_heightmap](https://user-images.githubusercontent.com/42042756/135517069-9883946a-280e-49ce-a308-ddafddde2478.png)

**Comment by darksylinc** [comment]
Hi!

This is with Ogre2 engine?

**Comment by mjcarroll** [comment]
> This is with Ogre2 engine?

Yes, this was discovered in preparation for the fortress/ign-rendering6 release.
