### ISSUE TITLE
Broken Jammy CI on downstream packages

### ISSUE THREAD

**Issue by methylDragon** [gazebosim/gz-rendering#627]
## Environment
* OS Version: Ubuntu Jammy 
* Binary build on Jammy CI with Jammy nightlies (`gz-rendering7` on `main`)

## Description
Something in Ogre2 changed that causes Jammy CI in downstream packages to have failing integration tests (e.g. `gz-sensors` segfaults on any test that uses the GPU.) The troublesome thing is this only happens on the CI, and can't be reproduced on a Jammy docker container.

It only occurs on Jammy CI, not Focal. This could be related to `OGRE-Next` or `OGRE2`, but I'm not too familiar with those packages.

This bug was discovered during the ignition -> gz migration, but is unrelated to that effort. Attempts at reverting any changes made still result in the tests segfaulting.

## Steps to reproduce

1. Build `rendering` nightlies with `main`
2. Run pull request CI on `sensors` using the `rendering` nightlies (such as here: https://github.com/gazebosim/gz-sensors/pull/221)
3. Watch the Jammy GitHub actions CI

## Output

From: https://github.com/gazebosim/gz-sensors/runs/6394835155?check_suite_focus=true
```
  Total Test time (real) =  15.35 sec
  
  The following tests FAILED:
  	 18 - INTEGRATION_depth_camera (SEGFAULT)
  	 22 - INTEGRATION_gpu_lidar_sensor (SEGFAULT)
  	 24 - INTEGRATION_rgbd_camera (SEGFAULT)
  Errors while running CTest
  	 26 - INTEGRATION_segmentation_camera (SEGFAULT)
  	 28 - INTEGRATION_thermal_camera (SEGFAULT)
  make: *** [Makefile:91: test] Error 8
```

**Comment by iche033** [comment]
gz-sensors rendering tests on Jammy should be fixed by https://github.com/gazebosim/gz-sensors/pull/324
