### ISSUE TITLE
Support wide-angle cameras in ogre2

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-rendering#729]
## Desired behavior

Support for wide-angle cameras was ported from gazebo-classic to gz-rendering's `ogre` (1.x) component in https://github.com/gazebosim/gz-rendering/pull/490. This ticket requests that it also be ported to the `ogre2` (2.x) component.

**Comment by darksylinc** [comment]
As I'm porting this to OgreWideAngleCamera to Ogre2; I noticed `OgreWideAngleCamera::Implementation::envCubeMapTextureFormat` **doesn't appear to be ever initialized**.

That looks like a bug?

**Comment by scpeters** [comment]
> As I'm porting this to OgreWideAngleCamera to Ogre2; I noticed `OgreWideAngleCamera::Implementation::envCubeMapTextureFormat` **doesn't appear to be ever initialized**.
> 
> That looks like a bug?
> 
> @iche033

that looks like a bug to me

**Comment by iche033** [comment]
> that looks like a bug to me
 
+1.

**Comment by darksylinc** [comment]
This ticket can be closed. PR #733 implemented this feature.
