### ISSUE TITLE
World origin visual

### ISSUE THREAD

**Issue by chapulina** [gazebosim/gz-rendering#73]
Create a world origin visual like [the one](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/OriginVisual.cc) from Gazebo-classic:

![origin](https://user-images.githubusercontent.com/5751272/80435722-34d2ae00-88b2-11ea-862f-b25dd2c5cab5.png)

Then integrate it into `ign-gazebo`.

**Comment by chapulina** [comment]
See https://github.com/ignitionrobotics/ign-gazebo/pull/150

**Comment by scpeters** [comment]
entity frames can be manually visualized as of https://github.com/gazebosim/gz-sim/pull/1105
