### ISSUE TITLE
Port LensFlare from gazebo-classic

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-rendering#730]
## Desired behavior

The lens flare behavior embodied in the [gazebo::rendering::LensFlare](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/LensFlare.hh) class should be supported in gz-rendering by the `ogre` and `ogre2` components. The following animation from [bitbucket pull request 2915](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2915/page/1) illustrates the effect.

![lens flare demonstration](https://osrf-migration.github.io/gazebo-gh-pages/data/bitbucket.org/repo/jgXqbo/images/798670463-lens_flare_occlusion_lossy.gif)

**Comment by azeey** [comment]
Closing since #752 and #775 have been merged.
