### ISSUE TITLE
metalness/roughness textures are wrong when these are embedded in the glb file.

### ISSUE THREAD

**Issue by ahcorde** [gazebosim/gz-rendering#772]
There is a bug with `metalness/roughness` textures when these are embedded in the `glb` file.

![Selection_102](https://user-images.githubusercontent.com/1933907/204760111-d386ae50-ca6b-4d98-9159-463712dedabf.png)

The texture is not being used

**Comment by iche033** [comment]
there have been a few glb related changes and this should be fixed.

https://github.com/gazebosim/gz-rendering/pull/931
https://github.com/gazebosim/gz-common/pull/532
https://github.com/gazebosim/gz-common/pull/538
