### ISSUE TITLE
Why does Scene::CreateCapsule not return GeometryPtr like the other shape methods?

### ISSUE THREAD

**Issue by Levi-Armstrong** [gazebosim/gz-rendering#856]
https://github.com/gazebosim/gz-rendering/blob/b0636118da33d252b374bc8ca0c24bcd3bf0e03d/include/gz/rendering/Scene.hh#L1028

**Comment by iche033** [comment]
A related comment here: https://github.com/gazebosim/gz-rendering/pull/200#pullrequestreview-589043823 and some discussions in the gz-common link in that comment.

 It is derived from a Geometry class though so can be cast to a `GeometryPtr`.
