### ISSUE TITLE
Gizmo uses a transform identifier not included in `TransformAxis`

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-rendering#880]
## Environment
* OS Version: all
* Source or binary build? all

## Description
* Expected behavior:  `GizmoVisual` uses a transform identifier defined in `TransformAxis`.
* Actual behavior: As seen in https://github.com/gazebosim/gz-rendering/blob/e58870ce3ea82711fc42777709e2170341b1eb3c/include/gz/rendering/base/BaseGizmoVisual.hh#L231, `GizmoVisual` uses `TransformAxis::TA_TRANSLATION_Z << 1` which is not documented.

**Comment by iche033** [comment]
hmm the logic there is to find a unique key that's not already used by `this->visuals`. I'll add some comments to it

**Comment by iche033** [comment]
Addressed by #881, and #882 (see related comment: https://github.com/gazebosim/gz-sim/pull/2051#discussion_r1296506004)
