### ISSUE TITLE
Collada file rendering with a blue tint when exported from Blender 2.82.

### ISSUE THREAD

**Issue by Levi-Armstrong** [gazebosim/gz-rendering#92]
I recently upgraded from Blender 2.79 to 2.82 and when exporting collada file from 2.82 they all have a blue tint to them in ignition rendering. I have attached a link from blender 2.79 and 2.82 along with an image.

[geom.zip](https://github.com/ignitionrobotics/ign-rendering/files/4707052/geom.zip)

![blender_282](https://user-images.githubusercontent.com/9803128/83343784-82cd3e00-a2c4-11ea-97c9-45a0a4ec3a6a.png)

**Comment by Levi-Armstrong** [comment]
@iche033 Do you have any thoughts on this? This can also be seen in my recent issue #810. I see different results when using ogre and ogre2.

**Comment by Levi-Armstrong** [comment]
Look at the content of the files version 2.79 outputs material using phong and version 2.82 uses lambert.

Version 2.79
``` xml
    <effect id="gray-effect">
      <profile_COMMON>
        <technique sid="common">
          <phong>
            <emission>
              <color sid="emission">0 0 0 1</color>
            </emission>
            <ambient>
              <color sid="ambient">0 0 0 1</color>
            </ambient>
            <diffuse>
              <color sid="diffuse">0.64 0.64 0.64 1</color>
            </diffuse>
            <specular>
              <color sid="specular">0.0125 0.0125 0.0125 1</color>
            </specular>
            <shininess>
              <float sid="shininess">205</float>
            </shininess>
            <index_of_refraction>
              <float sid="index_of_refraction">1</float>
            </index_of_refraction>
          </phong>
        </technique>
      </profile_COMMON>
    </effect>
```

Version 2.82
``` xml
    <effect id="gray-effect">
      <profile_COMMON>
        <technique sid="common">
          <lambert>
            <emission>
              <color sid="emission">0 0 0 1</color>
            </emission>
            <diffuse>
              <color sid="diffuse">0.64 0.64 0.64 1</color>
            </diffuse>
            <reflectivity>
              <float sid="specular">0.5</float>
            </reflectivity>
            <index_of_refraction>
              <float sid="ior">1</float>
            </index_of_refraction>
          </lambert>
        </technique>
      </profile_COMMON>
    </effect>
```

**Comment by Levi-Armstrong** [comment]
I noticed that all of the dae in gz-common do contain lambert materials but do not contain emission, reflectivity or index_of_reflectivity.

**Comment by Levi-Armstrong** [comment]
It looks like the current collada parser for lambert material does not process the following tags. Is this a issue?

- specular
- shininess
- index_of_refraction

**Comment by iche033** [comment]
ah I was wondering why your model appears blue in https://github.com/gazebosim/gz-rendering/issues/810 but I don't see that in mine.

I tested `link_3.dae` and `link_4.dae` and I don't get the blue tint though. 

I created a [`dae_blue_tint`](https://github.com/gazebosim/gz-rendering/compare/ign-rendering6...dae_blue_tint) branch to test this. I updated the `mesh_viewer` example to load your `link_3.dae` and `link_4.dae` in the geom.zip` file.

To build:

1. check out `dae_blue_tint` branch 
1. Go to `examples/mesh_viewer` dir and

    ```
    mkdir build
    cd build
    cmake ..
    make

    # run with ogre render engine
    ./mesh_viewer ogre

    # run with ogre2 render engine
    ./mesh_viewer ogre
    ```

ogre:

![dae_ogre1](https://user-images.githubusercontent.com/4000684/214709185-0c539d99-987e-441e-ab1e-8c3e8deacbd9.png)


ogre2:

![dae_ogre2](https://user-images.githubusercontent.com/4000684/214709196-b60050a9-2d02-4e9b-98b0-87f911fccd27.png)

**Comment by Levi-Armstrong** [comment]
@iche033 I have tracked down the cause of the blue tint. It is a result of the ambient tag not be provided. I have not tracked down in the code that is causing this but maybe this is something that has already been fixed on the latest branch. 

The lambert material causing blue tent.
``` xml
        <technique sid="common">
          <lambert>
            <emission>
              <color sid="emission">0 0 0 1</color>
            </emission>
            <diffuse>
              <color sid="diffuse">1 1 1 1</color>
            </diffuse>
            <index_of_refraction>
              <float sid="ior">1.45</float>
            </index_of_refraction>
          </lambert>
        </technique>
```

Fixed by adding the ambient tag
``` xml
        <technique sid="common">
          <lambert>
            <emission>
              <color sid="emission">0 0 0 1</color>
            </emission>
            <ambient>
              <color sid="ambient">0 0 0 1</color>
            </ambient>
            <diffuse>
              <color sid="diffuse">1 1 1 1</color>
            </diffuse>
            <index_of_refraction>
              <float sid="ior">1.45</float>
            </index_of_refraction>
          </lambert>
        </technique>
```

**Comment by Levi-Armstrong** [comment]
Well the change above only fixes it ogre and not ogre2.

**Comment by Levi-Armstrong** [comment]
If ambient is not provided for both ogre and ogre2 it defaults to [0.4 0.4 0.4 1]

**Comment by Levi-Armstrong** [comment]
@iche033, I was able to finally track down the root cause. In my case I was setting the scene ambient light to [0, 0, 1, 1] where gazebo sim sets it to [0.4, 0.4, 0.4, 1.0]. If I us the same values as gazebo the blue tint is gone in both ogre and ogre2 regardless of whether ambient is set for the mesh material, and if you set gazebo sim to use mine you will see the blue tint. Not sure if this is an indication of an issue or not.

**Comment by Levi-Armstrong** [comment]
More results with setting scene ambient light to Blue, Green and Red. I guess it makes sense now, but don't understand why only some models had the tent and other did not. 

**Scene Ambient Light [0, 0, 1, 1]**
![image](https://user-images.githubusercontent.com/9803128/214763068-6dfca373-b0ac-4ea5-af5e-323edcb56c22.png)

**Scene Ambient Light [0, 1, 0, 1]**
![image](https://user-images.githubusercontent.com/9803128/214763349-4c9a702d-6524-4ff2-9834-e20fa56627b9.png)

**Scene Ambient Light [1, 0, 0, 1]**
![image](https://user-images.githubusercontent.com/9803128/214763613-ec2819ea-eb9b-40d1-8d75-2955a0b38339.png)

**Comment by iche033** [comment]
> @iche033, I was able to finally track down the root cause. In my case I was setting the scene ambient light to [0, 0, 1, 1]

ok that makes sense! The blue tint on the objects as the result of blue ambient light is expected. The scene ambient light color will provide the "base color" for all objects in the scene.  The final color of an object is the combined result of the color of scene ambient light, color of other light sources (e.g. directional light), and color of the visual object itself.

> Well the change above only fixes it ogre and not ogre2.

Some differences between ogre 1.x and 2.x: 

* ogre 1.x uses Blinn-Phong shading where the color of visual object is determined by ambient, diffuse, and specular components. So when the `<color sid="ambient">0 0 0 1</color>` tag is present in the blender dae mesh, the combined (multiplied) ambient value is now zero ([0, 0, 1] *  [0, 0, 0]) so you don't see the blue tint.
* ogre 2.x uses PBR, which ignores the ambient component of the object, e.g. `visual->SetAmbient(...)` has no effect. The scene ambient lighting will still be applied so you see the blue tint.

**Comment by Levi-Armstrong** [comment]
Thanks for the explanation; it was very helpful. I think it is good to close this now.
