### ISSUE TITLE
What is the default gamma for ogre2

### ISSUE THREAD

**Issue by yagiztokgoz** [gazebosim/gz-rendering#927]
Hi, I have added a camera to my robot and streaming video to a python code. Looks like it is needed to add gamma correction for the camera capture. What is the value for Gazebo Ogre2?

![image](https://github.com/gazebosim/gz-rendering/assets/86158650/360cdcd0-a27e-4df1-b02c-d04b3a6e28f5)

**Comment by iche033** [comment]
the images from camera sensor should be the correct color / gamma settings. We're applying gamma on the Gazebo GUI window in QML to try match the colors from the camera sensor: https://github.com/gazebosim/gz-gui/blob/gz-gui7/src/plugins/minimal_scene/MinimalScene.qml#L60-L66
