### ISSUE TITLE
:farmer: Rendering Main failing after gz-cmake forward port

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-rendering#963]
## Environment
* OS Version: Ubuntu jammy
* Source Build

## Description
* Expected behavior: Build should pass
* Actual behavior: Build is failing

After https://github.com/gazebosim/gz-cmake/pull/399, gz-rendering7 was broken. @mjcarroll [solved this issue](https://github.com/gazebosim/gz-rendering/pull/950) for rendering7 branch.

The change that broke rendering7 was forward ported in https://github.com/gazebosim/gz-cmake/pull/401, so it makes sense that the issue is happening on main branch.

## Steps to reproduce
1. Run a build in https://build.osrfoundation.org/job/gz_rendering-ci-main-jammy-amd64/
2. See it fail.

## Output

Reference build: https://build.osrfoundation.org/job/gz_rendering-ci-main-jammy-amd64/24/

Log output:
```
[ 93%] [32m[1mLinking CXX shared library ../../lib/libgz-rendering9-ogre2.so[0m
/usr/bin/ld: ../../lib/libterra.a(OgreHlmsTerra.cpp.o): warning: relocation against `_ZN4Ogre11PbsProperty14LegacyMathBrdfE' in read-only section `.text'
/usr/bin/ld: ../../lib/libterra.a(OgreHlmsTerra.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN4Ogre9HlmsTerraE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [ogre2/src/CMakeFiles/gz-rendering9-ogre2.dir/build.make:987: lib/libgz-rendering9-ogre2.so.9.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:3493: ogre2/src/CMakeFiles/gz-rendering9-ogre2.dir/all] Error 2
```

**Comment by mjcarroll** [comment]
Resolved by #964
