### ISSUE TITLE
Fortress: Crash in Visualize Lidar when type is Points

### ISSUE THREAD

**Issue by peci1** [gazebosim/gz-rendering#970]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build? Binary 6.16
* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section. 
    - Rendering plugin: ogre, ogre2 (both affected) 
      - [x] Sensor rendering error. 
      - [ ] GUI rendering error. 
    - EGL headless mode:
      - [ ] Running in EGL headless mode 
    - Generally, mention all circumstances that might affect rendering capabilities: 
      - [ ] running on a dual GPU machine (integrated GPU + discrete GPU)
      - [ ] running on a multi-GPU machine (it has multiple discrete GPUs)
      - [x] running on real hardware
      - [ ] running in virtual machine
      - [ ] running in Docker/Singularity
      - [ ] running remotely (e.g. via SSH)
      - [ ] running in a cloud
      - [ ] using VirtualGL, XVFB, Xdummy, XVNC or other indirect rendering utilities
      - [x] GPU is concurrently used for other tasks
        - [x] desktop acceleration
        - [ ] video decoding (i.e. a playing Youtube video)
        - [ ] video encoding
        - [ ] CUDA/ROCm computations (Tensorflow, Torch, Caffe running)
        - [ ] multiple simulators running at the same time
      - [ ] other...
    - Rendering system info:
      - On Linux, provide the outputs of the following commands:

```bash
$ LANG=C lspci -nn | grep VGA  # might require installing pciutils
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [1002:1636] (rev d1)
$           echo "$DISPLAY"
:0
$           LANG=C glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'  # might require installing mesa-utils package
direct rendering: Yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.57, 6.7.5-060705-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.1 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.1 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.1 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
$           ps aux | grep Xorg
peci1       4438  1.0  0.3 1602564 99212 tty2    Sl+  úno22  73:58 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
peci1     670952  0.0  0.0  11600  2544 pts/5    S+   17:08   0:00 grep --color=auto Xorg
$           sudo env LANG=C X -version  # if you don't have root access, try to tell the version of Xorg e.g. via package manager
X.Org X Server 1.20.13
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux cras-17 6.7.5-060705-generic #202402161836 SMP PREEMPT_DYNAMIC Fri Feb 16 19:10:40 UTC 2024 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.7.5-060705-generic root=UUID=c8df4187-97f0-4be7-b095-39958ee965df ro quiet splash vt.handoff=7
Build Date: 29 January 2024  12:44:21PM
xorg-server 2:1.20.13-1ubuntu1~20.04.15 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```
 - [x] Please, attach the ogre.log or ogre2.log file from  `~/.gz/rendering` 

<details>

```
17:04:58: GLSL compile log: PointCloudVS_GLSL
0:33(2): error: `gl_PointSize' undeclared
0:33(2): error: value of type float cannot be assigned to variable of type error
17:04:58: OGRE EXCEPTION(3:RenderingAPIException): Vertex Program PointCloudVS_GLSL failed to compile. See compile log above for details. in GLSLShader::compile at /var/lib/jenkins/workspace/ogre-2.2-debbuilder/repo/RenderSystems/GL3Plus/src/GLSL/OgreGLSLShader.cpp (line 311)
```

</details>

## Description
* Expected behavior: 3D lidar can be visualized as points
* Actual behavior: Gazebo crashes due to `GLSL compile log: PointCloudVS_GLSL`

## Steps to reproduce

1. Add a 3D lidar.
2. Add Visualize Lidar plugin.
3. Select Points visualization type.

You can use the MWE SDF from #969 to test.

**Comment by iche033** [comment]
fixed by #1008
